name: Node CI
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS 24
        uses: actions/setup-node@v1
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org

      - name: Log Environment
        run: |
          echo "Node version $(node --version)"
          echo "NPM version $(npm --version)"
          echo "System Info $(uname -a)"

      - name: Install Dependencies
        run: npm ci

      - name: Format & Lint
        run: npm run check

      - name: Test
        run: npm test

      - name: Build prod
        run: npm run build

      - name: Build tests
        run: npm run build:tests
